# Generated by Django 5.1.2 on 2024-11-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loanofficer',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Age', models.IntegerField(primary_key='Age', serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('DoB', models.DateField()),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('typeofinterest', models.CharField(max_length=25)),
            ],
        ),
    ]
